apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-ingress-nginx-controller
  namespace: yahyeapps
data:
  use-forwarded-headers: "true"

  proxy-buffer-size: "4k"
  proxy-body-size: "10m"

  proxy-read-timeout: "3600"
  proxy-send-timeout: "3600"
  proxy-connect-timeout: "3600"

  enable-underscores-in-headers: "true"
  use-proxy-protocol: "false"
