apiVersion: apps/v1
kind: Deployment
metadata:
  name: yahyeapps-pg-bouncer
  namespace: yahyeapps

spec:
  replicas: 1

  selector:
    matchLabels:
      app: yahyeapps-pg-bouncer

  template:
    metadata:
      labels:
        app: yahyeapps-pg-bouncer

    spec:
      containers:
        - name: pgbouncer
          image: pgbouncer/pgbouncer:latest

          ports:
            - containerPort: 6432
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          volumeMounts:
            - name: pgbouncer-config
              mountPath: /etc/pgbouncer/pgbouncer.ini
              subPath: pgbouncer.ini

            - name: pgbouncer-users
              mountPath: /etc/pgbouncer/userlist.txt
              subPath: userlist.txt

          command: ["/usr/bin/pgbouncer", "/etc/pgbouncer/pgbouncer.ini"]

      volumes:
        - name: pgbouncer-config
          configMap:
            name: pgbouncer-config

        - name: pgbouncer-users
          secret:
            secretName: pgbouncer-users
