apiVersion: v1
kind: Service
metadata:
  name: yahyeapps-pg-bouncer-service
  namespace: yahyeapps

spec:
  selector:
    app: yahyeapps-pg-bouncer

  ports:
    - protocol: TCP
      port: 6432
      targetPort: 6432

  type: ClusterIP
