apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-yahyeapps
  namespace: yahyeapps

spec:
  serviceName: "postgres-yahyeapps"
  replicas: 1

  selector:
    matchLabels:
      app: postgres-yahyeapps

  template:
    metadata:
      labels:
        app: postgres-yahyeapps

    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999

      containers:
        - name: postgres-yahyeapps
          image: postgres:17

          env:
            - name: TZ
              value: "Africa/Mogadishu"

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: yahyeapps-postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yahyeapps-postgres-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: yahyeapps-postgres-secret
                  key: POSTGRES_DB

          ports:
            - containerPort: 5432

          resources:
            requests:
              memory: "3Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2"

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

            # init scripts
            - name: postgres-init-script-volume
              mountPath: /docker-entrypoint-initdb.d/
              readOnly: true

            # custom postgres config
            - name: postgres-config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf

          command:
            - "postgres"

          args:
            - "-c"
            - "config_file=/etc/postgresql/postgresql.conf"

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgress-pvc-yahyeapps

        - name: postgres-init-script-volume
          configMap:
            name: postgres-init-script

        - name: postgres-config
          configMap:
            name: postgres-custom-config
