apiVersion: v1
kind: PersistentVolume
metadata:
  name: yahyeapps-postgress-pv
  namespace: yahyeapps
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard-pv-yahyeapps
  hostPath:
    path: /db/yahyeapps-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgress-pvc-yahyeapps
  namespace: yahyeapps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-pv-yahyeapps
  resources:
    requests:
      storage: 10Gi
