apiVersion: v1
kind: Service
metadata:
  name: postgres-yahyeapps
  namespace: yahyeapps
spec:
  selector:
    app: postgres-yahyeapps
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432