apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-forward-proxy
  namespace: yahyeapps
data:
  default.conf: |
    server {
        listen 3128;

        resolver 1.1.1.1 8.8.8.8 9.9.9.9 valid=30s ipv6=off;
        location / {

            # =========================
            # 🔐 SECURITY CHECK (IMPORTANT)
            # =========================

            if ($http_x_yahyeapps_verify != $ALLOWED_REQUEST_TOKEN) {
                return 403 "Forbidden";
            }

            proxy_pass http://$host$request_uri;

            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
