apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: yahyeapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 3128

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          env:
            - name: ALLOWED_REQUEST_TOKEN
              valueFrom:
                secretKeyRef:
                  name: allowed-request-token
                  key: allowed_request_token

          command:
            - /bin/sh
            - -c
            - |
              envsubst '$ALLOWED_REQUEST_TOKEN' \
              < /etc/nginx/templates/default.conf.template \
              > /etc/nginx/conf.d/default.conf

              nginx -g 'daemon off;'

          volumeMounts:
            - name: nginx-template
              mountPath: /etc/nginx/templates

      volumes:
        - name: nginx-template
          configMap:
            name: nginx-proxy-config
