name: "Deploy "

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read
  security-events: write

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  # ----------------------------
  # 5️⃣ Docker Build & Push
  # ----------------------------
  docker:
    runs-on: ubuntu-latest
    if: github.event.head_commit.message == 'deploy'
    timeout-minutes: 20 # Maximum running time for this job
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT_TOKEN }} # Fixed typo: was DOCKER_PAT_TOKEN

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: ./server-setup/self-hosted-github-runners
          push: true
          tags: |
            ${{vars.DOCKER_GIT_ACTION_RUNNER_REPO}}:${{ env.IMAGE_TAG }}
            ${{vars.DOCKER_GIT_ACTION_RUNNER_REPO}}:latest

  server:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # Maximum running time for this job
    needs: [docker]
    steps:
      - uses: actions/checkout@v4

      - name: Update image tag in deployment FOR git-actions-self-hosted-runner
        run: |
          if [ -f "server-setup/self-hosted-github-runners/deploment.yml" ]; then
            sed -i "s|image: ${{vars.DOCKER_GIT_ACTION_RUNNER_REPO}}.*|image: ${{vars.DOCKER_GIT_ACTION_RUNNER_REPO}}:${{ env.IMAGE_TAG }}|g" \
              server-setup/self-hosted-github-runners/deploment.yml
            echo "✅ Updated deployment.yaml to use image: ${{ vars.DOCKER_GIT_ACTION_RUNNER_REPO }}:${{ env.IMAGE_TAG }}"
          else
            echo "⚠️ Warning: server-setup/self-hosted-github-runners/deploment.yml not found, skipping inline update"
          fi

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_WITH_NO_PASSPHRASE }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST_IP }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          if ! ssh -o BatchMode=yes \
              -o ConnectTimeout=10 \
              -i ~/.ssh/id_rsa \
              ${{ vars.SSH_USER }}@${{ secrets.SSH_HOST_IP }} \
              "echo Connected successfully"
          then
            echo "❌ SSH connection failed, is this user created in in server (github-actions)  "
            exit 1
          fi

      - name: Copy files to server
        run: |
          scp -o BatchMode=yes -o ConnectTimeout=10 \
          -i ~/.ssh/id_rsa -r ./server-setup \
          ${{ vars.SSH_USER }}@${{ secrets.SSH_HOST_IP }}:/tmp

      - name: Run full server setup on remote machine
        run: |
          ssh -i ~/.ssh/id_rsa ${{ vars.SSH_USER }}@${{ secrets.SSH_HOST_IP }} <<EOF
            set -euo pipefail
            
            #skip this if server already configured .  
            if [ -f /home/${{vars.SSH_USER}}/.server-ready ]; then
              echo "Server already configured"
              exit 0
            fi

            echo 'export PATH=/usr/sbin:/sbin:/usr/bin:/bin:$PATH' >> ~/.bashrc 

            cd /tmp 
            

            echo "🚀 Starting server setup..."

            # ========================
            # 1. Make scripts executable
            # ========================
            find server-setup -type f -name "*.sh" -exec chmod +x {} +


            # chage namespace in yaml 
            find server-setup \( -name "*.yml" -o -name "*.yaml" \) \
             -exec sed -i "s|^[[:space:]]*namespace: .*|  namespace: ${{ vars.NAMESPACE }}|g" {} +

            # ========================
            # 2. Server config
            # ========================

           

            echo "${{secrets.SUDO_PASSWORD}}" | sudo -S bash -c '

            set -euo pipefail

            echo "soodhoow yahye" | tee /etc/motd

            apt-get update -y
            apt-get install -y ufw cron git curl

            cp /tmp/server-setup/server-config/update-cloudflare-ufw.sh /usr/local/bin/
            chmod +x /usr/local/bin/update-cloudflare-ufw.sh

            echo "0 0 * * * /usr/local/bin/update-cloudflare-ufw.sh >/dev/null 2>&1" | crontab -

            echo 'export PATH=/usr/sbin:/sbin:/usr/bin:/bin:$PATH' >> ~/.bashrc 
            source ~/.bashrc
            bash /usr/local/bin/update-cloudflare-ufw.sh

            # ======================
            # k3s install
            # ======================
            curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik" sh -

            chmod 644 /etc/rancher/k3s/k3s.yaml
            chown ${{vars.SSH_USER}}:${{vars.SSH_USER}} /etc/rancher/k3s/k3s.yaml

            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
            # ======================
            # sysctl tuning
            # ======================
            sed -i "/# WEB SOCKET TUNING START/,/# WEB SOCKET TUNING END/d" /etc/sysctl.conf

            cat >> /etc/sysctl.conf <<EOF
            # WEB SOCKET TUNING START
            net.core.somaxconn=65535
            net.ipv4.tcp_max_syn_backlog=65535
            net.ipv4.ip_local_port_range=1024 65535
            net.ipv4.tcp_fin_timeout=10
            net.ipv4.tcp_tw_reuse=1
            net.ipv4.tcp_max_tw_buckets=5000000
            fs.file-max=5000000
            # WEB SOCKET TUNING END
            EOF

            sysctl --system

            # ======================
            # limits
            # ======================
            for file in /etc/security/limits.conf /etc/systemd/system.conf /etc/systemd/user.conf; do
              sed -i "/# WEB SOCKET TUNING START/,/# WEB SOCKET TUNING END/d" "$file"

              cat >> "$file" <<EOF
            # WEB SOCKET TUNING START
            * soft nofile 1000000
            * hard nofile 1000000
            * soft nproc 100000
            * hard nproc 100000
            DefaultLimitNOFILE=1000000
            DefaultLimitNPROC=100000
            # WEB SOCKET TUNING END
            EOF
            done

            systemctl daemon-reexec

            echo "✅ Server setup completed"
            exit
            '

            echo 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml' >> ~/.bashrc   
            source ~/.bashrc
            # ========================
            # 3. Nginx + Redis
            # ========================
            export NAMESPACE=${{ vars.NAMESPACE }}

            /tmp/server-setup/ngnix/install.sh
            kubectl apply -f /tmp/server-setup/ngnix/nginx-config.yaml

            /tmp/server-setup/redis/install.sh

            # ========================
            # 4. Cert Manager
            # ========================
            kubectl create secret generic cloudflare-api-token \
              -n cert-manager \
              --from-literal=api-token='${{ secrets.CLOUDFLARE_PAT_TOKEN }}' \
              --dry-run=client -o yaml | kubectl apply -f -



                
            /tmp/server-setup/cert-manager/install.sh
            kubectl apply -f /tmp/server-setup/cert-manager/issuer-cluster-letsencrtypt.yml

            # ========================
            # 5. Postgres secret
            # ========================
            kubectl create secret generic yahyeapps-postgres-secret \
              -n ${{ vars.NAMESPACE }} \
              --from-literal=POSTGRES_USER='${{ secrets.PG_USER }}' \
              --from-literal=POSTGRES_PASSWORD='${{ secrets.PG_PASSWORD }}' \
              --from-literal=POSTGRES_DB='${{ secrets.PG_DB }}' \
              --from-literal=POSTGRES_HOST='${{ secrets.PG_HOST }}' \
              --from-literal=POSTGRES_PORT='${{ secrets.PG_PORT }}' \
              --dry-run=client -o yaml | kubectl apply -f -

            # ========================
            # 6. Postgres + PgBouncer + Envoy
            # ========================
            kubectl create secret generic allowed-request-token \
              -n ${{ vars.NAMESPACE }} \
              --from-literal=allowed_request_token='${{ secrets.ALLOWED_REQUEST_TOKEN }}' \
              --dry-run=client -o yaml | kubectl apply -f -

            kubectl apply -f /tmp/server-setup/postgres
            kubectl apply -f /tmp/server-setup/pg_bouncer
            kubectl apply -f /tmp/server-setup/proxy-envoy

            echo "✅ Server setup completed successfully"

            # ========================
            # 6. self hosted runner 
            # ========================
            kubectl create secret generic github-runner-token \
            -n ${{ vars.NAMESPACE }} \
            --from-literal=RUNNER_TOKEN='${{ secrets.SELF_HOSTED_RUNNER_TOKEN }}' \
            --dry-run=client -o yaml | kubectl apply -f -
            kubectl apply -f /tmp/server-setup/self-hosted-github-runners/deploment.yml


            # clear sudo password cache
            echo "ready" > /home/${{vars.SSH_USER}}/.server-ready

            EOF
