apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy

metadata:
  name: enforce-cluster-proxy

spec:
  selector: all()

  namespaceSelector: projectcalico.org/name not in {"kube-system", "cert-manager"}

  types:
    - Egress

  egress:
    - action: Allow
      protocol: TCP
      destination:
        namespaceSelector: projectcalico.org/name == "yahyeapps"
        selector: app == "envoy"
        ports:
          - 8080

  applyOnForwarded: true
