apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: enforce-cluster-proxy

spec:
  selector: projectcalico.org/namespace not in {
    "kube-system",
    "cert-manager"
  }

  types:
    - Egress

  egress:
    - action: Allow
      destination:
        namespaceSelector: kubernetes.io/metadata.name == "yahyeapps"
        selector: app == "envoy"
        ports:
          - 8080

  applyOnForwarded: true